### ISSUE TITLE
Groups are not allowed to have parenthesis in their name

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/ldapauthenticator#151]
I extracted this from @leetim's issue #148 where two issues were described in one github issue, making it hard to track them properly. Below is the issue as described by @leetim in #148.

---

Users cannot be authorized if the group name contains the characters `(` and `)`.

```python
c.LDAPAuthenticator.allowed_groups = [
 'CN=_ IT-группа Бизнес-анализа данных,OU=_ДолжностиИОтделы,OU=DNS Users,DC=partner,DC=ru',
 # Authorization with next line doesn't work
 'CN=_ Федеральный директор - Фед. адм. (Управление),OU=_ДолжностиИОтделы,OU=DNS Users,DC=partner,DC=ru',
]
```

**Comment by csayler** [comment]
yes, we ran into the same problem...

**Comment by kinow** [comment]
Strange, that worked for me. My group name is `dn: cn=admin (2),ou=roles,dc=wimpi,dc=net`. My settings have:

```
c.LDAPAuthenticator.allowed_groups = [
    "cn=admin (2),ou=roles,dc=wimpi,dc=net"
]
```

And when I debug the authenticator, it's possible to confirm that the LDAP search used that value in the filters (I had to remove `memberUid` and `uniqueMember` due to #133 as I'm using OpenLDAP).

![image](https://user-images.githubusercontent.com/304786/86984218-10644d80-c1e2-11ea-9bd2-59d438c83680.png)

**Comment by consideRatio** [comment]
There is recent escaping effort made that could have helped, and a comment about it may actually work even before that. I'll go for a close.
